name: home_away_dashboard
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  cloud_firestore: ^4.4.3
  cupertino_icons: ^1.0.2
  data_table_2: ^2.2.1
  file_picker: ^5.2.5
  firebase_auth: ^4.2.2
  firebase_core: ^2.7.0
  firebase_storage: ^11.0.14
  flutter:
    sdk: flutter
  flutter_screenutil: 5.6.1
  get: ^4.6.5
  google_fonts: ^4.0.3
  intl: ^0.18.0
  url_strategy: ^0.2.0
  flutter_rating_bar: ^4.0.0
  flutter_easyloading: ^3.0.3


dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
  uses-material-design: true
