// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaxKAutGMFHDaw7BP2jZ-rEYh7x_K_kbQ',
    appId: '1:624078817325:web:acb7c31d085e46d48a90a4',
    messagingSenderId: '624078817325',
    projectId: 'storeappliaction',
    authDomain: 'storeappliaction.firebaseapp.com',
    storageBucket: 'storeappliaction.appspot.com',
    measurementId: 'G-VSYW1FL3KQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNGSgZ-QrynelFDVERCfv1r0x4f9VW2x8',
    appId: '1:624078817325:android:8efd78b9f41bcf968a90a4',
    messagingSenderId: '624078817325',
    projectId: 'storeappliaction',
    storageBucket: 'storeappliaction.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf5eV2cF4oYYx06gRmpU81LkD7-naqQZk',
    appId: '1:624078817325:ios:5fa58d82b94536fd8a90a4',
    messagingSenderId: '624078817325',
    projectId: 'storeappliaction',
    storageBucket: 'storeappliaction.appspot.com',
    iosClientId: '624078817325-tl5uorhg90f9fnthmbt2ie3uq3tha3rt.apps.googleusercontent.com',
    iosBundleId: 'com.example.homeAwayDashboard',
  );
}
